services:  
  nginx:  
    image: nginx:alpine  
    volumes:  
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  
      - v:/usr/share/nginx/html  
    ports:  
      - '80:80'  
    restart: always  
    depends_on:  
      - front  

  front:  
    build:  
      context: ./front
      dockerfile: Dockerfile  
    volumes:  
      - v:/app/build  ахах
    depends_on:  
      - back  

  back:  
    build:  
      context: ./back
      dockerfile: Dockerfile  
    ports:  
      - "5000:5000"  

volumes:  
  v:  