services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - volume1:/usr/share/nginx/html
    ports:
      - '80:80'
    restart: always
    depends_on:
      - front

  front:
    build:
        dockerfile: ./front/Dockerfile
    volumes:
      - volume1:/app/build
    depends_on:
      - back
  back:
    build: 
        dockerfile: ./back/Dockerfile
    ports:
      - "5000:5000"
volumes:
  volume1: